---
client:
  enabled: true
  pullPolicy: IfNotPresent
  name: fortio-client
  namespace: fortio
  nodeSelector: {}
  replicas: 1
  resources: {}

server:
  enabled: true
  pullPolicy: IfNotPresent
  name: fortio-server
  namespace: fortio
  nodeSelector: {}
  affinity:
    podAntiAffinity: {}
  replicas: 1
  resources: {}

  hpa:
    enabled: false
    maxReplicas: 3
    minReplicas: 1
    targetCPUUtilizationPercentage: 80

istio:
  envoyStats: false
  envoyStatsInclusionPrefixes: cluster.outbound
  mtls: true
  sidecarInjection: true
  sidecarCpuLimit: false
  sidecarCpuLimitValue: "1"
