deployment:
  pullPolicy: IfNotPresent
  replicas: 1
  resources: {}
  affinity:
    node: {}
    pod: {}
    pod_anti: {}
  tolerations: []
  nodeSelector: {}

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

k6:
  duration: 2m
  requestSize: "50"
  targerUrl: "http://service1:9091/"
  virtualUsers: "10"

service:
  account: k6
  name: k6
  version: 1.0.0
