apiVersion: v2
appVersion: 1.0.0
description: A Helm chart for k6, an http load testing tool
engine: gotpl
keywords:
  - istio
  - aspenmesh
  - performance
  - benchmark
  - js
  - k6
maintainers:
  - name: Bart Van Bos
    email: bartvanbos@gmail.com
name: k6
sources: 
  - https://k6.io
type: application
version: 1.0.0
