---
apiVersion: v1
kind: Service
metadata:
  name: fortio-client
  namespace: fortio
  labels:
    app: fortio-client
spec:
  ports:
  - port: 8080
    name: http
    targetPort: http-fortio
    nodePort: 30020
  - port: 8079
    name: http2
    targetPort: grpc-ping
  selector:
    app: fortio-client
  type: NodePort
