---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-client
  namespace: fortio
  labels:
    app: fortio-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio-client
  template:
    metadata:
      annotations:
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound
      labels:
        app: fortio-client
    spec:
      containers:
      - name: fortio
        image: fortio/fortio:latest_release
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping
      nodeSelector:
        kubernetes.io/hostname: worker3
