---
{{- if .Values.client.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.name }}
  namespace: {{ .Values.client.namespace }}
  labels:
    app: {{ .Values.client.name }}
spec:
  ports:
  - port: 8080
    name: http
    targetPort: http-fortio
    nodePort: 30020
  - port: 8079
    name: http2
    targetPort: grpc-ping
  selector:
    app: {{ .Values.client.name }}
  type: NodePort
{{- end }}
