---
{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.name }}
  namespace: {{ .Values.client.namespace }}
  labels:
    app: {{ .Values.client.name }}
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.client.name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "{{ .Values.istio.sidecarInjection }}"
        {{- if .Values.istio.sidecarInjection }}
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        {{- end }}
        {{- if .Values.istio.envoyStats }}
        sidecar.istio.io/statsInclusionPrefixes: "{{ .Values.istio.envoyStatsInclusionPrefixes }}"
        {{- end }}
        {{- if .Values.istio.sidecarCpuLimit }}
        sidecar.istio.io/proxyCPULimit: "{{ .Values.istio.sidecarCpuLimitValue }}"
        {{- end }}
      labels:
        app: {{ .Values.client.name }}
    spec:
      containers:
      - name: fortio
        image: fortio/fortio:latest_release
        imagePullPolicy: {{ .Values.client.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping
        {{- if .Values.server.resources }}
        resources:
        {{- toYaml .Values.server.resources | nindent 10 }}
        {{- end }}
      {{- if .Values.client.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.client.nodeSelector | nindent 8 }}
      {{- end }}
{{- end }}
