---
{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Values.server.namespace }}
  labels:
    app: {{ .Values.server.name }}
spec:
  ports:
  - port: 8080
    name: http
    targetPort: http-fortio
  - port: 8079
    name: http2
    targetPort: grpc-ping
  selector:
    app: {{ .Values.server.name }}
{{- end }}
