---
{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Values.server.namespace }}
  labels:
    app: {{ .Values.server.name }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.server.name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "{{ .Values.istio.sidecarInjection }}"
        {{- if .Values.istio.sidecarInjection }}
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        {{- end }}
        {{- if .Values.istio.envoyStats }}
        sidecar.istio.io/statsInclusionPrefixes: "{{ .Values.istio.envoyStatsInclusionPrefixes }}"
        {{- end }}
      labels:
        app: {{ .Values.server.name }}
    spec:
      containers:
      - name: fortio
        image: fortio/fortio:latest_release
        imagePullPolicy: {{ .Values.server.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping
          {{- if .Values.server.resources }}
          resources:
          {{- toYaml .Values.server.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.server.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.server.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.server.affinity.pod_anti }}
      affinity:
        podAntiAffinity:
        {{- toYaml .Values.server.affinity.pod_anti | nindent 10 }}
      {{- end }}
{{- end }}
