groups:
  - name: Health Score Alert
    rules:
    - alert: Health Score Threshold Exceeded
      expr: avg by (destination_workload, destination_workload_namespace) (aspenmesh_application_health_score{destination_workload_namespace!="unknown"}) < 0.50
      annotations:
        namespaceId: '{{ $labels.destination_workload_namespace }}'
        workloadId: '{{ $labels.destination_workload }}'
        healthScoreThreshold: 0.50
        healthScore: '{{ $value }}'
