--- 
aspen-mesh-controlplane: 
  clusterId: PerfTest
  userAuth: 
    jwt: 
      jwks: "https://YOUR_DOMAIN/.well-known/jwks.json"
      redirectUrl: "https://YOUR_DOMAIN/login"
    type: none
aspen-mesh-event-storage: 
  affinity: 
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms: 
          - matchExpressions: 
              - key: role
                operator: In
                values: 
                  - aspenmesh
    podAntiAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
        - labelSelector: 
            matchExpressions: 
              - key: app
                operator: In
                values: 
                  - aspen-mesh-event-storage
          topologyKey: kubernetes.io/hostname
aspen-mesh-packet-inspector: 
  analysis: 
    address: "aspen-mesh-analysis-emulator.analysis-emulator:21000"
  enabled: false
aspen-mesh-secure-ingress: 
  enabled: true
  externalDnsEnabled: false
  lets-encrypt-email: ""
cert-manager: 
  nodeSelector:
    role: aspenmesh
  cainjector: 
    nodeSelector:
      role: aspenmesh
  webhook: 
    nodeSelector:
      role: aspenmesh
citadel: 
  enabled: true
external-dns: 
  enabled: false
gateways: 
  istio-egressgateway: 
    enabled: true
    env: 
      ISTIO_META_REQUESTED_NETWORK_VIEW: external
  istio-ingressgateway: 
    debug: debug
    enabled: true
    type: ClusterIP
global: 
  certificateCustomFields: true
  defaultNodeSelector: 
    role: aspenmesh
  proxy: 
    accessLogEncoding: TEXT
    accessLogFile: /dev/stdout
    accessLogFormat: "{ \"authority\": \"%REQ(:AUTHORITY)%\", \"bytes_received\": %BYTES_RECEIVED%, \"bytes_sent\": %BYTES_SENT%, \"downstream_local_address\": \"%DOWNSTREAM_LOCAL_ADDRESS%\", \"downstream_peer_cert_v_end\": \"%DOWNSTREAM_PEER_CERT_V_END%\", \"downstream_peer_cert_v_start\": \"%DOWNSTREAM_PEER_CERT_V_START%\", \"downstream_remote_address\": \"%DOWNSTREAM_REMOTE_ADDRESS%\", \"downstream_tls_cipher\": \"%DOWNSTREAM_TLS_CIPHER%\", \"downstream_tls_version\": \"%DOWNSTREAM_TLS_VERSION%\", \"duration\": %DURATION%, \"hostname\": \"%HOSTNAME%\", \"istio_policy_status\": \"%DYNAMIC_METADATA(istio.mixer:status)%\", \"method\": \"%REQ(:METHOD)%\", \"path\": \"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%\", \"protocol\": \"%PROTOCOL%\", \"request_duration\": %REQUEST_DURATION%, \"request_id\": \"%REQ(X-REQUEST-ID)%\", \"requested_server_name\": \"%REQUESTED_SERVER_NAME%\", \"response_code\": \"%RESPONSE_CODE%\", \"response_duration\": %RESPONSE_DURATION%, \"response_tx_duration\": %RESPONSE_TX_DURATION%, \"response_flags\": \"%RESPONSE_FLAGS%\", \"route_name\": \"%ROUTE_NAME%\", \"start_time\": \"%START_TIME%\", \"upstream_cluster\": \"%UPSTREAM_CLUSTER%\", \"upstream_host\": \"%UPSTREAM_HOST%\", \"upstream_local_address\": \"%UPSTREAM_LOCAL_ADDRESS%\", \"upstream_service_time\": %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%, \"upstream_transport_failure_reason\": \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\", \"user_agent\": \"%REQ(USER-AGENT)%\", \"x_forwarded_for\": \"%REQ(X-FORWARDED-FOR)%\" } \n"
jaeger: 
  cassandra: 
    selector:
      nodeSelector:
        role: aspenmesh
    enabled: true
    fullnameOverride: aspen-mesh-cassandra
  collector: 
    nodeSelector:
      role: aspenmesh
  enabled: true
  query: 
    nodeSelector:
      role: aspenmesh
  storage:
    cassandra:
      nameOverride: aspen-mesh-cassandra
meshConfig:
  enablePrometheusKubernetesMetrics: true
pilot:
  nodeSelector:
    role: aspenmesh
prometheus: 
  enabled: true
